name: Build

on:
  push:
    branches:
    - main

jobs:
  build-sdist:
    name: Build source dist
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python-version: 3.12
    - name: Build sources
      run: |-
        pip install build wheel
        python -mbuild -n -s
    - name: Upload sources
      uses: actions/upload-artifact@v4
      with:
        name: dist-sources
        path: dist/*.tar.gz
        retention-days: 2

  build-wheels:
    name: Build wheel on ${{runner.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python-version: '3.9'
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16
      with:
        output-dir: dist
      env:
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_TEST_SKIP: '*arm64 *aarch64'
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
        name: dist-wheels-${{matrix.os}}
        retention-days: 2
