name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  clone_vendors:
    name: Clone vendors (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install tree-sitter cli
      run: npm install -g tree-sitter-cli

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install Dependencies
      run: uv sync --no-install-project

    - name: Create parsers directory
      run: mkdir -p parsers

    - name: Clone vendors
      run: uv run --no-sync scripts/clone_vendors.py

    - name: Upload Parsers
      uses: actions/upload-artifact@v4
      with:
        name: language-parsers-${{ matrix.os }}
        path: parsers

  validate:
    needs: clone_vendors
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download parsers
      uses: actions/download-artifact@v4
      with:
        name: language-parsers-${{ matrix.os }}
        path: parsers

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install Dependencies
      run: uv sync --no-install-project

    - name: Load Cached Pre-Commit Dependencies
      id: cached-pre-commit-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run Linters
      run: uv run --no-sync pre-commit run --show-diff-on-failure --color=always --all-files
  test:
    needs: clone_vendors
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download parsers
      uses: actions/download-artifact@v4
      with:
        name: language-parsers-${{ matrix.os }}
        path: parsers

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install Dependencies
      run: uv sync --no-install-project

    - name: Cache Bindings
      id: cache-bindings
      uses: actions/cache@v4
      with:
        path: tree_sitter_language_pack/bindings
        key: ${{ hashFiles('sources/*') }}-language-definitions

    - name: Build Extensions
      if: steps.cache-bindings.outputs.cache-hit != 'true'
      run: uv run --no-sync setup.py build_ext --inplace

    - name: Test
      shell: bash
      run: uv run --no-sync pytest tests -v
      env:
        PROJECT_ROOT: ${{github.workspace}}
